

server:
  port: 18085

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: service-gateway
  config:
    import:
      - optional:nacos:gateway.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: nacos-route
          uri: lb://service-student
          predicates:
            Path=/config/**
